title: This is just the beginning
author: BystrovaV
email: your-email@domain.com
description: > This is awesome lesson about Github Pages.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
